version: '3.4'

services:
  ocelot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=${OCELOT_EXT_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERT_DEFAULT_PW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    ports:
      - "${OCELOT_EXT_PORT}:80"
      - "${OCELOT_EXT_HTTPS_PORT}:443"      
    volumes:
      - ~/.aspnet/https:/https:ro
  
  patient-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=${PATIENT_SERVICE_EXT_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERT_DEFAULT_PW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ConnectionStrings__DefaultConnection=Server=${PATIENT_DB_SERVER_NAME},${PATIENT_DB_PORT_INT};Initial Catalog=${PATIENT_DB_INITIAL_CATALOG};User Id=${PATIENT_DB_USER_ID};Password=${PATIENT_DB_PASSWORD}"
      - "RabbitMQ__HostName=${RABBITMQ_HOSTNAME}"
      - "RabbitMQ__User=${RABBITMQ_USER}"
      - "RabbitMQ__Password=${RABBITMQ_PASSWORD}"
    ports:
      - "${PATIENT_SERVICE_EXT_PORT}:80"
      - "${PATIENT_SERVICE_EXT_HTTPS_PORT}:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  booking-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=${BOOKING_SERVICE_EXT_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERT_DEFAULT_PW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ConnectionStrings__DefaultConnection=Server=${BOOKING_DB_SERVER_NAME},${BOOKING_DB_PORT_INT};Initial Catalog=${BOOKING_DB_INITIAL_CATALOG};User Id=${BOOKING_DB_USER_ID};Password=${BOOKING_DB_PASSWORD}"
      - "RabbitMQ__HostName=${RABBITMQ_HOSTNAME}"
      - "RabbitMQ__User=${RABBITMQ_USER}"
      - "RabbitMQ__Password=${RABBITMQ_PASSWORD}"
      - "ExternalPatientApi__Protocol=http"
      - "ExternalPatientApi__HostName=patient-service"
      - "ExternalPatientApi__Port=${PATIENT_SERVICE_INT_HTTP_PORT}"
    ports:
      - "${BOOKING_SERVICE_EXT_PORT}:80"
      - "${BOOKING_SERVICE_EXT_HTTPS_PORT}:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  booking-db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD_SEED}
      - MSSQL_PID=Express
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-USA", "-P${SA_PASSWORD_SEED}", "-Q", "SELECT 1"]
    ports:  
      - "${BOOKING_DB_PORT_EXT}:${BOOKING_DB_PORT_INT}"
    volumes:
      - booking-db-sqldata:/var/opt/mssql
      - booking-db-sqluser:/var/opt/sql

  patient-db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD_SEED}
      - MSSQL_PID=Express
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-USA", "-P${SA_PASSWORD_SEED}", "-Q", "SELECT 1"]
    ports:  
      - "${PATIENT_DB_PORT_EXT}:${PATIENT_DB_PORT_INT}"
    volumes:
      - patient-db-sqldata:/var/opt/mssql
      - patient-db-sqluser:/var/opt/sql

  blazor-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=${BLAZOR_SERVER_EXT_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERT_DEFAULT_PW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "RabbitMQ__HostName=${RABBITMQ_HOSTNAME}"
      - "RabbitMQ__User=${RABBITMQ_USER}"
      - "RabbitMQ__Password=${RABBITMQ_PASSWORD}"
    ports:
      - "${BLAZOR_SERVER_EXT_PORT}:80"
      - "${BLAZOR_SERVER_EXT_HTTPS_PORT}:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  rabbitmq:
    user: rabbitmq
    environment: 
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        - RABBITMQ_NODENAME=${RABBITMQ_NODENAME}
        - RABBITMQ_USER=${RABBITMQ_USER}
        - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
        - "${RABBITMQ_EXT_PORT_1}:5672"
        - "${RABBITMQ_EXT_PORT_2}:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/logs/:/var/log/rabbitmq/