version: '3.4'

services:
  booking-service:
    build:
      context: .
      dockerfile: Services/CalHealth.BookingService/src/Dockerfile
    depends_on: 
      - booking-db
      - kibana

  calendar-service:
    build:
      context: .
      dockerfile: Services/CalHealth.CalendarService/src/Dockerfile
    depends_on: 
      - calendar-db
      - kibana

  calendar-db:
    image: "mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04"

  booking-db:
    image: "mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04"

  blazor-server:
    build:
      context: .
      dockerfile: Client/CalHealth.Blazor/Server/Dockerfile

  rabbitmq:
    build: 
      context: .
      dockerfile: Infrastructure/RabbitMQ/Dockerfile
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    depends_on:
      - elasticsearch

volumes:
  rabbitmq:
  elasticsearch-data:
  calendar-db-sqldata:
    external: false
  calendar-db-sqluser:
    external: false
  booking-db-sqldata:
    external: false
  booking-db-sqluser:
    external: false
    