version: '3.4'

services:
  booking-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=${BOOKING_SERVICE_EXT_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERT_DEFAULT_PW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "${BOOKING_SERVICE_EXT_PORT}:80"
      - "${BOOKING_SERVICE_EXT_HTTPS_PORT}:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  calendar-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=${CALENDAR_SERVICE_EXT_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERT_DEFAULT_PW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "${CALENDAR_SERVICE_EXT_PORT}:80"
      - "${CALENDAR_SERVICE_EXT_HTTPS_PORT}:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  calendar-db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD_SEED}
      - MSSQL_PID=Express
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-USA", "-P${SA_PASSWORD_SEED}", "-Q", "SELECT 1"]
    ports:  
      - "${CALENDAR_DB_PORT_EXT}:${CALENDAR_DB_PORT_INT}"
    volumes:
      - calendar-db-sqldata:/var/opt/mssql
      - calendar-db-sqluser:/var/opt/sql

  booking-db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD_SEED}
      - MSSQL_PID=Express
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-USA", "-P${SA_PASSWORD_SEED}", "-Q", "SELECT 1"]
    ports:  
      - "${BOOKING_DB_PORT_EXT}:${BOOKING_DB_PORT_INT}"
    volumes:
      - booking-db-sqldata:/var/opt/mssql
      - booking-db-sqluser:/var/opt/sql

  blazor-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=${BLAZOR_SERVER_EXT_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERT_DEFAULT_PW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "${BLAZOR_SERVER_EXT_PORT}:80"
      - "${BLAZOR_SERVER_EXT_HTTPS_PORT}:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  rabbitmq:
    environment: 
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        - RABBITMQ_NODENAME=${RABBITMQ_NODENAME}
        - RABBITMQ_USER=${RABBITMQ_USER}
        - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
        - "${RABBITMQ_EXT_PORT_1}:5672"
        - "${RABBITMQ_EXT_PORT_2}:15672"
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - ./rabbitmq/data/mnesia:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/logs/:/var/log/rabbitmq/

volumes:
  rabbitmq:
  calendar-db-sqldata:
    external: false
  calendar-db-sqluser:
    external: false
  booking-db-sqldata:
    external: false
  booking-db-sqluser:
    external: false
