version: '3.4'

services:
  ocelot:
    build:
      context: .
      dockerfile: Infrastructure/CalHealth.Ocelot/Dockerfile
  
  patient-service:
    build:
      context: .
      dockerfile: Services/CalHealth.PatientService/src/Dockerfile
    depends_on: 
      - patient-db
      - rabbitmq

  booking-service:
    build:
      context: .
      dockerfile: Services/CalHealth.BookingService/src/Dockerfile
    depends_on: 
      - booking-db
      - rabbitmq

  booking-db:
    image: "mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04"

  patient-db:
    image: "mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04"

  blazor-server:
    build:
      context: .
      dockerfile: Client/CalHealth.Blazor/Server/Dockerfile

  rabbitmq:
    build: 
      context: .
      dockerfile: Infrastructure/RabbitMQ/Dockerfile
    restart: always

volumes:
  rabbitmq:
  booking-db-sqldata:
    external: false
  booking-db-sqluser:
    external: false
  patient-db-sqldata:
    external: false
  patient-db-sqluser:
    external: false
    